=== Blitz-BS/blitzCollection/json_schema/case.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/Blitz-BS/blitzCollection/refs/heads/main/json_schema/case.schema.json",
    "title": "Dossier",
    "description": "Dossier dans le cadre d'un contrat",
    "required": [ "contractId", "reference","creditor","debtors","entries"],
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "title" : "Schéma JSON",
            "description" : "URL du schéma",
            "type": "string",
            "format": "uri"
        },
        "contractId" : {
            "title" : "Identifiant du contrat",
            "description" : "Identifiant du contrat entre la société de recouvrement et son client. Il s'agit de l'identifiant unique dans Blitz Collection",
            "type" : "integer"
        },
        "reference" : {
            "title" : "Référence",
            "description" : "Référence du dossier chez le client de la société de recouvrement. Cette référence doit être unique pour un client et un créancier donné.",
            "type": "string"
        },
        "creditor": {
            "title": "Créancier",
            "$ref": "./person.schema.json"
        },
        "debtors": {
            "title" : "Débiteurs",
            "description": "Débiteur ou co-débiteurs et leurs engagements respectifs. Si l'engagement n'est pas rempli, la situation est solidaire",
            "type": "array",
            "minItems": 1,
            "items": {
                "$ref": "./debtor.schema.json"
            }
        },
        "guarantors": {
            "title": "Cautions",
            "description": "Cautions du dossier et leurs engagements respectifs. Si l'engagement n'est pas rempli, la caution est solidaire",
            "type": "array",
            "items": {
                "$ref": "./debtor.schema.json"
            }
        },
        "entries": {
            "title": "Écritures",
            "description": "Écriture comptables du dossier",
            "type": "array",
            "minItems": 1,
            "items": {
                "oneOf" : [
                    {
                        "$ref": "./debt.schema.json"
                    },
                    {
                        "$ref": "./payment.schema.json"
                    },
                    {
                        "$ref": "./creditNote.schema.json"
                    },
                    {
                        "$ref": "./incidental.schema.json"
                    },
                    {
                        "$ref": "./adjustment.schema.json"
                    },
                    {
                        "$ref": "./closing.schema.json"
                    }
                ]
            }
        },
        "parties":{
            "title": "Tiers",
            "description": "Tiers impliqués dans le dossier",
            "items": {
                "$ref": "./person.schema.json"           
            }
        },
        "currencyCode" : {
            "title" : "Code devise",
            "description" : "Code devise du dossier. Ce code est la devise par défaut du dossier",
            "$ref" : "./currencyCode.schema.json"
        },
        "legislation": {
            "title" : "Legislation",
            "description" : "Législation utilisée pour les frais accessoires. Code ISO 3166-1",
            "default": "FR",
            "enum" : ["af", "ax", "al", "dz", "as", "ad", "ao", "ai", "aq", "ag", "ar", "am", "aw", "au", "at", "az", "bs", "bh", "bd", "bb", "by", "be", "bz", "bj", "bm", "bt", "bo", "bq", "ba", "bw", "bv", "br", "io", "bn", "bg", "bf", "bi", "cv", "kh", "cm", "ca", "ky", "cf", "td", "cl", "cn", "cx", "cc", "co", "km", "cg", "cd", "ck", "cr", "ci", "hr", "cu", "cw", "cy", "cz", "dk", "dj", "dm", "do", "ec", "eg", "sv", "gq", "er", "ee", "sz", "et", "fk", "fo", "fj", "fi", "fr", "gf", "pf", "tf", "ga", "gm", "ge", "de", "gh", "gi", "gr", "gl", "gd", "gp", "gu", "gt", "gg", "gn", "gw", "gy", "ht", "hm", "va", "hn", "hk", "hu", "is", "in", "id", "ir", "iq", "ie", "im", "il", "it", "jm", "jp", "je", "jo", "kz", "kz", "kz", "kp", "kr", "kw", "kg", "la", "lv", "Lb", "ls", "lr", "ly", "li", "lt", "lu", "mo", "mg", "mw", "my", "mv", "ml", "mt", "mh", "mq", "mr", "mu", "yt", "mx", "fm", "md", "mc", "mn", "me", "ms", "ma", "mz", "mm", "nr", "np", "nl", "nc", "nz", "ni", "ne", "ng", "nu", "nf", "mk", "mp", "no", "om", "pk", "pw", "ps", "pa", "pg", "py", "pe", "ph", "pn", "pl", "pt", "pr", "qa", "re", "ro", "ru", "rw", "bl", "sh", "kn", "lc", "mf", "pm", "vc", "ws", "sm", "st", "sa", "sn", "rs", "sc", "sl", "sg", "sx", "sk", "si", "sb", "so", "za", "gs", "ss", "es", "lk", "sd", "sr", "sj", "se", "ch", "sy", "tw", "tj", "tz", "th", "tl", "tg", "tk", "to", "tt", "tn", "tr", "tm", "tc", "tv", "ug", "ua", "ae", "gb", "us", "um", "uy", "uz", "vu", "ve", "vn", "vg", "vi", "wf", "eh", "ye", "zm", "zw"]
        }
    }
}

=== Blitz-BS/blitzCollection/examples/folder.example.json
{
    "$schema": "https://raw.githubusercontent.com/Blitz-BS/blitzCollection/refs/heads/main/json_schema/folder.schema.json",
    "contractId" : 123456,
    "reference": "123456789",
    "creditor" : {
        "reference" : "123456789",
        "name": "Blitz Business Service",
        "personCategory": "legal person",
        "companyInfo": {
            "companyRegistrationNumber": "401694989",
            "mainAddress": {
                "street": "265 rue Denis Papin",
                "city": "Villefontaine",
                "postalCode": "38090",
                "countryCode": "FR"
            },
            "companyPhone": {
                "value": "04 74 96 27 34",
                "qualification": "professional"
            },
            "companyEmail": {
                "value": "contact@blitzbs.com",
                "qualification": "professional"
            },
            "repository": "https://annuaire-entreprises.data.gouv.fr/entreprise/blitz-business-services-par-abreviation-blitz-bs-401694989"
        },
        "contacts": [
            {
                "role": "commercial",
                "reference" : "A123456789",
                "civility": "monsieur",
                "lastName": "Durant",
                "firstName": "Paul",
                "phones": [
                    {
                        "value": "01 02 03 04 05",
                        "qualification": "professional"
                    }
                ],
                "emails": [
                    {
                        "value": "pdurant@blitzbs.com",
                        "qualification": "professional"
                    }
                ],
                "languageCode": "fra"
            }
        ],
        "bankAccount": {
            "name": "Compte de l'entreprise",
            "iban": "FR7630006000011234567890189",
            "bank": "Banque de France",
            "bankCode": "30006",
            "sortCode": "00123",
            "accountNumber": "12345678901",
            "key": "89"
        }
    },
    "debtors" : [
        {
            "value": {
                "reference" : "B123456789",
                "name": "Monsieur Jean Dupont",
                "personCategory": "natural person",
                "contacts": [
                    {
                        "value": {
                            "reference" : "C123456789",
                            "civility": "monsieur",
                            "lastName": "Dupont",
                            "firstName": "Jean",
                            "phones": [
                                {
                                    "value": "02 03 04 05 06",
                                    "qualification": "professional"
                                },
                                {
                                    "value": "06 01 02 03 04",
                                    "qualification": "personal"
                                }
                            ],
                            "emails": [
                                {
                                    "value": "jdupont@monmail.com",
                                    "description": "Adresse peu utilis√©e",
                                    "qualification": "professional"
                                }
                            ],
                            "adresses": [
                                {
                                    "street": "Rue de la paix",
                                    "city": "Paris",
                                    "postalCode": "75000",
                                    "countryCode": "FR"
                                }
                            ],
                            "languageCode": "fra"
                        }
                    }
                ]
            }
        }
    ],
    "guarantors": [
        {
            "value": {
                "reference" : "B123456789",
                "name": "Jeanne Dupont",
                "personCategory": "natural person",
                "contacts": [
                    {
                        "value": {
                            "reference" : "C123456789",
                            "civility": "madame",
                            "lastName": "Dupont",
                            "firstName": "Jeanne",
                            "phones": [
                                {
                                    "value": "02 03 04 05 06",
                                    "qualification": "professional"
                                },
                                {
                                    "value": "06 01 02 03 04",
                                    "qualification": "personal"
                                }
                            ],
                            "emails": [
                                {
                                    "value": "jdupont@monmail.com",
                                    "qualification": "professional"
                                }
                            ],
                            "adresses": [
                                {
                                    "street": "Rue de la paix",
                                    "city": "Paris",
                                    "postalCode": "75000",
                                    "countryCode": "FR"
                                }
                            ],
                            "languageCode": "fra"
                        }
                    }
                ]
            }
        }
    ],
    "entries" : [
        {
            "category" : "debt",
            "subcategory": "invoice",
            "reference" : "F123456789",
            "label" : "Facture 2021-01",
            "entryDate": "2021-01-01",
            "dueDate": "2021-01-31",
            "amount" : 1000,
            "vatAmount": 200,
            "interestRate" : 0.05,
            "letterings": [
                {
                    "entryReference" : "F123456789",
                    "amount" : 1000
                }
            ]
        },
        {
            "$schema": "https://raw.githubusercontent.com/Blitz-BS/blitzCollection/refs/heads/main/json_schema/payment.schema.json",
            "category" : "payment",
            "subcategory": "payment",
            "reference" : "P1258",
            "label" : "paiement partiel de la facture F123456789",
            "entryDate": "2021-03-02",
            "paymentDate" : "2021-03-01",
            "amount" : -50,
            "method" : "creditCard",
            "issuingPersonReference" : "123456789",
            "recipientPersonReference" : "0011223344",
            "letterings": [
                {
                    "entryReference" : "F123456789",
                    "amount" : -50
                }
            ]
        }
    ],
    "parties" : [{
        "reference" : "C123456789",
        "name": "GBA Avocats",
        "personCategory": "legal person",
        "ability" : "attorney",
        "companyInfo": {
            "companyRegistrationNumber": "493675904",
            "mainAddress": {
                "street": "24 MAIL FRANCOIS MITTERRAND",
                "city": "RENNES",
                "postalCode": "35000",
                "countryCode": "FR"
            },
            "companyPhone": {
                "value": "02 99 35 12 12",
                "qualification": "professional"
            },
            "companyEmail": {
                "value": "gba@gba-avocats.com",
                "qualification": "professional"
            },
            "companyForm": "SA",
            "repository": "https://annuaire-entreprises.data.gouv.fr/entreprise/493675904"
        },
        "contacts": [
            {
                "role": "avocat fiscaliste",
                "reference" : "D123456789",
                "civility": "madame",
                "lastName": "Duplessis",
                "firstName": "Marie",
                "phones": [
                    {
                        "value": "02 02 03 04 05",
                        "qualification": "professional"
                    }
                ],
                "emails": [
                    {
                        "value": "mduplessis@gba-avocats.com",
                        "qualification": "professional"
                    }
                ],
                "languageCode": "fra"
            }
        ]
    }],
    "currencyCode": "EUR"
}
