=== Blitz-BS/blitzCollection/json_schema/companyInfo.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/Blitz-BS/blitzCollection/refs/heads/MGP-421-modularisation-de-l-objet-json-schema-pour-l-integ/json_schema/companyInfo.schema.json",
    "title": "Informations sur une entreprise",
    "description": "Informations utiles sur une entreprise",
    "anyOf": [
        {"required": ["companyRegistrationNumber"]},
        {"required": ["mainAddress"]}
    ],
    "additionalProperties": false,
    "type": "object",
    "properties": {
        "$schema": {
            "title" : "Schéma JSON",
            "description" : "URL du schéma",
            "type": "string",
            "format": "uri"
        },
        "companyRegistrationNumber" : {
            "title" : "Numéro d'immatriculation",
            "description" : "Numéro d'immatriculation de l'entreprise",
            "type": "string",
            "maxLength": 21
        },
        "mainAddress" : {
            "title" : "Adresse principale",
            "description" : "Adresse principale de l'entreprise",
            "$ref": "./address.schema.json"
        },
        "billingAddress" : {
            "title" : "Adresse de facturation",
            "description" : "Adresse de facturation de l'entreprise",
            "$ref": "./address.schema.json"
        },
        "headOfficeAddress" : {
            "title" : "Adresse du siège social",
            "description" : "Adresse du siège social de l'entreprise",
            "$ref": "./address.schema.json"
        },
        "entreprisePhone" : {
            "title" : "Numéro de téléphone de l'entreprise",
            "description" : "Numéro de téléphone de l'entreprise",
            "$ref": "./phone.schema.json"
        },
        "entrepriseEmail" : {
            "title" : "Adresse email de l'entreprise",
            "description" : "Adresse email de l'entreprise",
            "$ref": "./email.schema.json"
        },
        "parentCompany" : {
            "title" : "Maison mère",
            "description" : "Maison mère de l'entreprise",
            "$ref": "./person.schema.json"
        },
        "repository" : {
            "title" : "Registre des sociétés",
            "description" : "Page de registre des sociétés. Exemple : https://annuaire-entreprises.data.gouv.fr/entreprise/blitz-business-services-par-abreviation-blitz-bs-401694989",
            "type": "string",
            "format": "uri"
        }
    }
}

=== Blitz-BS/blitzCollection/examples/companyInfo.example.json
{
    "companyRegistrationNumber": "401694989",
    "mainAddress": {
        "street": "265 rue Denis Papin",
        "city": "Villefontaine",
        "postalCode": "38090",
        "countryCode": "FR"
    },
    "entreprisePhone": {
        "value": "04 74 96 27 34",
        "isMobile": false,
        "qualification": "professional"
    },
    "entrepriseEmail": {
        "value": "contact@blitzbs.com",
        "qualification": "professional"
    },
    "repository": "https://annuaire-entreprises.data.gouv.fr/entreprise/blitz-business-services-par-abreviation-blitz-bs-401694989"
}
